name: deploy react app

on:
    push:
        branches: [main]

# remember the basics and you will understand every code in your mind


jobs:
    build-and-publish:
        name: Build and Publish Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: checkout source
              uses: actions/checkout@v3
            - name: Build the docker image
              run: docker build --file Dockerfile --tag uyadav585/reactjs-app:${{ github.sha }} --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_SERVER_BASE_URL=${{ secrets.REACT_APP_SERVER_BASE_URL }} .

            - name: Publish to Registry
              uses: elgohr/Publish-Docker-Github-Action@v4
              with:
                name: uyadav585/reactjs-app
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                tags: "latest,${{ github.sha }}"



    deploy:
        needs: build-and-publish
        runs-on: self-hosted
        steps:
            - name: Ensure Docker socket permissions
              run:  sudo chmod 666 /var/run/docker.sock
            - name: remove running container
              run:  docker rm -f reactjs-app-container
            - name: clean up waste docker images
              run : docker rmi $(docker images -q | grep -v $(docker ps --format '{{.Image}}' | xargs -n 1 docker images --format '{{.ID}}' --filter=reference | tr '\n' '|'))
            - name: pull image from dockerhub
              run:  docker pull uyadav585/reactjs-app:${{ github.sha }}
            - name: run docker container
              run:  docker run -d -p 3000:80 --name reactjs-app-container uyadav585/reactjs-app:${{ github.sha }}
            